Simplify token handling
nasa/opera-sds-pcm pull request #275
Opened 2022-10-25 19:05 UTC by maseca

Closes #274

2022-10-25 19:58 UTC, chrisjrd requested changes

2022-10-25 19:58 UTC, chrisjrd commented on data_subscriber/daac_data_subscriber.py
> +    if not (
consider performing this check sooner before making any network requests (handle token), for efficiency reasons. Think of it as input validation.

2022-10-25 19:58 UTC, chrisjrd commented on data_subscriber/daac_data_subscriber.py
> +def handle_token(edl: str, username: str, password: str) -> str:
consider renaming, as handle token is too generic. It also isn't handling a token param, as the name might imply. Maybe you can use `get_token` or `supply_token` (taken from frameworks that use supplier/consumer terms). I'd use `fetch_token` for something that does the network call.

2022-10-25 19:58 UTC, chrisjrd commented on data_subscriber/daac_data_subscriber.py
> +    if not token_list:
there is a slim chance that the list may contain an expired token. that scenario would break this code. consider filtering the list for valid tokens before using in the if expression.

2022-10-25 19:58 UTC, chrisjrd commented on data_subscriber/daac_data_subscriber.py
> +def handle_token(edl: str, username: str, password: str) -> str:
it is not clear what `edl` is. consider adding documentation comment explaining the format of the str param. e.g. `URL`, `ISO 8601 string`, `_ JSON string`, etc.

2022-10-25 19:58 UTC, chrisjrd commented on data_subscriber/daac_data_subscriber.py
> +    token_list_url = f"https://{edl}/api/users/tokens"
this can probably be moved to a global. but if the implementation doesn't make this feasible, don't worry about it.

2022-10-25 19:58 UTC, chrisjrd commented on data_subscriber/daac_data_subscriber.py
> +def _process_token_list(token_list: list, edl: str, username: str, password: str) -> None:
for completeness, consider writing the type hint as `list[str]`. For some lists, it is obvious what the type is for readers. But being complete would help with IDE usage. I leave it up to you.

2022-10-25 19:58 UTC, chrisjrd commented on data_subscriber/daac_data_subscriber.py
> +def _process_token_list(token_list: list, edl: str, username: str, password: str) -> None:
consider renaming. for now, proces token list appears to just delete expired tokens. you could rename this to `revoke_expired_tokens` or something for added clarity.

2022-10-25 19:58 UTC, chrisjrd commented on data_subscriber/daac_data_subscriber.py
> +        logging.warning("Failed to acquire CMR token")
because this condition results in an exception being thrown, consider not logging at the `warning` level. you can simply let the exception bubble up and the error be expressed in the exception message.

2022-10-25 19:58 UTC, chrisjrd commented on data_subscriber/daac_data_subscriber.py
>          else:
consider writing the response here, or elaborating the the type of failure. Because there is a difference between a client error (deleting an expired token) and an internal server error (500). The current implementation would swallow any CMR server error, making it harder to troubleshoot.

2022-10-25 19:58 UTC, chrisjrd commented on tests/data_subscriber/test_daac_data_subscriber.py
>          mock_token_ctx
consider renaming, as there is no longer a token context.

2022-10-25 21:16 UTC, maseca commented on data_subscriber/daac_data_subscriber.py
> +def handle_token(edl: str, username: str, password: str) -> str:
Sure

2022-10-25 21:35 UTC, maseca commented on data_subscriber/daac_data_subscriber.py
> +    if not token_list:
Ah, I did delete the token via the API but I forgot to delete the list entry. How does this look? 
```python
def _process_token_list(token_list: list, edl: str, username: str, password: str) -> None:
    for token_dict in token_list:
        now = datetime.utcnow().date()
        expiration_date = datetime.strptime(token_dict['expiration_date'], "%m/%d/%Y").date()

        if expiration_date <= now:
            _delete_token(edl, username, password, token_dict['access_token'])
            del token_dict # New code
```

2022-10-25 21:39 UTC, maseca commented on data_subscriber/daac_data_subscriber.py
> +    token_list_url = f"https://{edl}/api/users/tokens"
Want to leave it there in case it needs to be changed to provide more context

2022-10-25 21:43 UTC, maseca commented on data_subscriber/daac_data_subscriber.py
>          else:
```python
            logging.warning(f"CMR token deletion failed: {resp.status_code=}")
```

2022-10-25 22:09 UTC, chrisjrd approved these changes

2022-10-25 22:09 UTC, chrisjrd commented
lgtm

2022-10-26 21:37 UTC, hhlee445 commented
@maseca The unit test failed with following msg and wan't able to deploy the PCM successfully. Please take a look and retest.
module.common.null_resource.install_pcm_and_pges (remote-exec): [opera-pcm-ci.jpl.nasa.gov] out:
module.common.null_resource.install_pcm_and_pges (remote-exec): [opera-pcm-ci.jpl.nasa.gov] out: =========================== short test summary info ============================
module.common.null_resource.install_pcm_and_pges (remote-exec): [opera-pcm-ci.jpl.nasa.gov] out: FAILED tests/data_subscriber/test_daac_data_subscriber.py::test_full - FileNo...
module.common.null_resource.install_pcm_and_pges (remote-exec): [opera-pcm-ci.jpl.nasa.gov] out: FAILED tests/data_subscriber/test_daac_data_subscriber.py::test_query - FileN...
module.common.null_resource.install_pcm_and_pges (remote-exec): [opera-pcm-ci.jpl.nasa.gov] out: FAILED tests/data_subscriber/test_daac_data_subscriber.py::test_query_chunked
module.common.null_resource.install_pcm_and_pges (remote-exec): [opera-pcm-ci.jpl.nasa.gov] out: FAILED tests/data_subscriber/test_daac_data_subscriber.py::test_query_no_schedule_download
module.common.null_resource.install_pcm_and_pges (remote-exec): [opera-pcm-ci.jpl.nasa.gov] out: FAILED tests/data_subscriber/test_daac_data_subscriber.py::test_query_smoke_run
module.common.null_resource.install_pcm_and_pges (remote-exec): [opera-pcm-ci.jpl.nasa.gov] out: FAILED tests/data_subscriber/test_daac_data_subscriber.py::test_download - Fi...
module.common.null_resource.install_pcm_and_pges (remote-exec): [opera-pcm-ci.jpl.nasa.gov] out: FAILED tests/data_subscriber/test_daac_data_subscriber.py::test_download_by_tile
module.common.null_resource.install_pcm_and_pges (remote-exec): [opera-pcm-ci.jpl.nasa.gov] out: FAILED tests/data_subscriber/test_daac_data_subscriber.py::test_download_by_tiles
module.common.null_resource.install_pcm_and_pges (remote-exec): [opera-pcm-ci.jpl.nasa.gov] out: FAILED tests/data_subscriber/test_daac_data_subscriber.py::test_download_https
module.common.null_resource.install_pcm_and_pges (remote-exec): [opera-pcm-ci.jpl.nasa.gov] out: FAILED tests/data_subscriber/test_daac_data_subscriber.py::test_download_by_tiles_smoke_run
module.common.null_resource.install_pcm_and_pges (remote-exec): [opera-pcm-ci.jpl.nasa.gov] out: FAILED tests/data_subscriber/test_daac_data_subscriber.py::test_download_by_tiles_dry_run
module.common.null_resource.install_pcm_and_pges (remote-exec): [opera-pcm-ci.jpl.nasa.gov] out: ================= 11 failed, 37 passed, 15 warnings in 12.86s ==================
module.common.aws_lambda_function.event-misfire_lambda: Still creating... [4m0s elapsed]

2022-10-27 18:39 UTC, hhlee445 commented
@maseca SLC data download doesn't work with this fix. Can you take a look?

2022-10-27 18:57 UTC, hhlee445 commented
@maseca  batch_ids for SLC data  download job shows as '--batch-ids _043900_', we should remove '_' from it.

2022-10-27 20:08 UTC, hhlee445 approved these changes

2022-10-27 20:09 UTC, merged