Issue 478: SLC ionosphere file download and CSLC submission
nasa/opera-sds-pcm pull request #525
Opened 2023-06-16 18:13 UTC by chrisjrd

2023-06-20 22:24 UTC, collinss-jpl requested changes
Overall approach looks solid, but I had some concerns regarding the core loop over the SLC datasets in ionosphere_download.py. See my comments below.

2023-06-20 22:24 UTC, collinss-jpl commented on data_subscriber/ionosphere_download.py
> +                if results["fail"]:
Not sure `results["fail"]` is what you want to always be checking here. For example, if two jobs are to be submitted and the first fails (and is added to `results["fail"]`), the second job would also trigger this condition even if it was successful, since `results` is not cleared between iterations of the loop.

Maybe this should be checking `job_submission_results["fail"]` instead? In that case lines 90-93 could be merged into the conditional branch at line 85?

2023-06-20 22:24 UTC, collinss-jpl commented on data_subscriber/ionosphere_download.py
> +                    exceptions.extend(results["fail"])
Again, I think you want to call `extensions.extend(job_submission_results["fail"])` instead of using `results['fail']`, since `results` is cumulative, and thus could results in redundant entries in `exceptions` for every failed job.

2023-06-20 22:24 UTC, collinss-jpl commented on data_subscriber/ionosphere_download.py
> +                job_submission_results = await submit_cslc_jobs([slc_dataset], args)
Since `submit_cslc_jobs` is set up to work on multiple job requests at a time, lines 81-93 could be moved outside of this loop and only called once using the entire list of `slc_dataset` that we got ionosphere files for.

2023-06-20 23:28 UTC, chrisjrd commented on cluster_provisioning/modules/common/variables.tf
> +      "instance_type" = ["c5n.2xlarge", "m5dn.2xlarge"]
No thought. I jut copy-pasted from the top. We previously had issues with another job using medium size (probably due to RAM). We can use something like m6a.large or m6i.large to get the work done.

2023-06-20 23:29 UTC, chrisjrd commented on data_subscriber/download.py
> +                and (additional_metadata['processing_mode'] == "historical" or additional_metadata['processing_mode'] == "reprocessing"):
I'm not sure where this came from, but I'll make the change.

2023-06-20 23:33 UTC, chrisjrd commented on data_subscriber/ionosphere_download.py
> +                    and slc_dataset["_source"]["metadata"].get("processing_mode") == "forward":
the previous if statement functions as a guard clause. This one, while redundant, was meant to highlight or make more visible the conditions that trigger the body of work (code) inside it. I can remove it if you'd like, but i think it makes it easier to reason about the code when reading it, despite it being redundant.

2023-06-20 23:34 UTC, chrisjrd commented on data_subscriber/ionosphere_download.py
> +                if results["fail"]:
i'll take another look. The code is meant to be accumulating and grouping the successes and failures, so if it isn't doing that, i'll need to fix it.

2023-06-20 23:36 UTC, chrisjrd commented on data_subscriber/ionosphere_download.py
> +                job_submission_results = await submit_cslc_jobs([slc_dataset], args)
i'll take closer look

2023-06-20 23:45 UTC, chrisjrd commented on data_subscriber/ionosphere_download.py
> +                if results["fail"]:
yes. this should be checking the local variable inside the loop. not the one outside. fixing.

I'm not sure about combining them. One block is meant to group the results, while the other one is directly part of the exception handling. There is a more concise way of writing the first block, but it escapes me what it is (similar in functionality to a dict comprehension, but may be more of a map or reduce).

i can combine them, but i wanted to keep them as distinct blocks since i felt they were performing different functions. Think about maybe if we extracted the blocks into their own functions. The functions would be more "pure" (one input to one output/action) if their functionalities were not combined.

yes, we can combine them since they share the conditional, but i'm looking at it in terms of grouping the statements by their purpose.

2023-06-21 19:55 UTC, collinss-jpl commented on data_subscriber/ionosphere_download.py
> +@backoff.on_exception(backoff.expo, exception=Exception, max_tries=3, jitter=None, giveup=lambda e: isinstance(e, IonosphereFileNotFoundException))
Does this `giveup` clause need to be added to the url-only version of this function below?

2023-06-21 19:57 UTC, collinss-jpl approved these changes
Major issues have been addressed. I think this branch could be merged now.

2023-06-21 21:56 UTC, chrisjrd commented on data_subscriber/ionosphere_download.py
> +@backoff.on_exception(backoff.expo, exception=Exception, max_tries=3, jitter=None, giveup=lambda e: isinstance(e, IonosphereFileNotFoundException))
no, but it will definitely close any gaps and prevent any issues from the asymmetry with the other function. fixing.

2023-06-21 22:47 UTC, hhlee445 approved these changes

2023-06-22 00:09 UTC, hhlee445 approved these changes

2023-06-22 00:11 UTC, merged