add uat option to validator script and document in readme
nasa/opera-sds-pcm pull request #779
Opened 2024-03-29 19:24 UTC by niarenaw

## Purpose
- Update dswx-s1-validator code to address R3 calval use cases
## Proposed Changes
- [ADD] endpoint option to specify OPS or UAT CMR venue
- [UPDATE] README to address new argument
- [UPDATE] README to fix iso timestamps in example

## Testing
- Code has been used with R3 calval data

2024-03-30 00:03 UTC, riverma commented
Thanks a ton @niarenaw for your contribution! Let me test this out against some of our existing test cases and then get to approving / merging 👍

2024-04-01 18:44 UTC, riverma requested changes
Thank you for this contribution @niarenaw - excellent!

Couple suggestions inline but two I wanted to add:
- Did you make the regex fix to allow the `S1B` RTC granules to work? If so could you contribute that to this PR and rename the PR / purpose accordingly?
- UAT CMR has less granules than OPS, and I noticed that many times no granules are returned. I think we should add a `sys.exit(1)` right after [this line](https://github.com/nasa/opera-sds-pcm/blob/issue-703-r3-calval/report/dswx-s1-validator/dswx_s1_validator.py#L204) since now this is a common occurrence. Would you consider adding that?

2024-04-01 18:44 UTC, riverma commented on report/dswx-s1-validator/README.md
> +Querying CMR for time range 2023-12-05T01:00:00 to 2023-12-05T03:59:59.
I think we should keep the `Z` as that denotes times are expected to be in UTC.

2024-04-01 18:44 UTC, riverma commented on report/dswx-s1-validator/dswx_s1_validator.py
> +    parser.add_argument("--endpoint", required=False, choices=['UAT', 'OPS'], default='OPS', help='CMR endpoint venue')
Nice that you've given a default 💯

2024-04-01 18:44 UTC, riverma commented on report/dswx-s1-validator/dswx_s1_validator.py
> +        if args.endpoint == 'UAT':
🥇

2024-04-04 20:54 UTC, niarenaw commented on report/dswx-s1-validator/README.md
> +Querying CMR for time range 2023-12-05T01:00:00 to 2023-12-05T03:59:59.
I get a ValueError, when including `Z`: `ValueError: Invalid isoformat string: '2023-12-05T01:00:00Z'`

2024-04-04 21:04 UTC, niarenaw commented
@riverma thanks for you suggested changes -- I've added them.

2024-04-15 20:49 UTC, hhlee445 approved these changes

2024-04-15 21:46 UTC, hhlee445 commented
@niarenaw @riverma i'm trying to merge this PR, however, there are some conflict. @riverma can you help to resolve the conflicts?

2024-05-02 22:01 UTC, riverma commented
Thanks @niarenaw for the additions! I've made a couple improvements to enhance the reliability. Was getting a number of granule query batch failures, but I think that's fixed now. Will merge. Thanks @hhlee445 as well.

2024-05-02 22:03 UTC, riverma approved these changes
Thanks @niarenaw for your help improving this script!

2024-05-02 22:03 UTC, merged